#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : Keras
Version  : 1.2.2
Release  : 1
URL      : https://pypi.python.org/packages/75/3e/9926ce5c678b7a7978724a2ecf24857d89a415d152b8d3443e6d45c228b2/Keras-1.2.2.tar.gz
Source0  : https://pypi.python.org/packages/75/3e/9926ce5c678b7a7978724a2ecf24857d89a415d152b8d3443e6d45c228b2/Keras-1.2.2.tar.gz
Summary  : Deep Learning for Python
Group    : Development/Tools
License  : MIT
Requires: Keras-python
BuildRequires : PyYAML
BuildRequires : Theano
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : six
BuildRequires : tensorflow

%description
No detailed description available

%package python
Summary: python components for the Keras package.
Group: Default
Provides: keras-python

%description python
python components for the Keras package.


%prep
%setup -q -n Keras-1.2.2

%build
export LANG=C
export SOURCE_DATE_EPOCH=1486914133
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1486914133
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
